[package]
name = "goose_gremlin"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.56.0", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging"] }
enigo = "0.1"
winit = "0.29"